version: "3.8"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8888:8888"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./odoo/odoo:/usr/lib/python3/dist-packages/odoo
      - ./odoo/addons:/mnt/addons
      - ./enterprise-addons:/mnt/enterprise-addons
      - ./custom-addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: